msFilterList
# Title: My TPL
: Expires=100
-d interactions.vnexpress.net
-d polyad.net
-d eclick.vn
-d da2.ad.zing.vn
-d image.mp3.zdn.vn
-d zaloapp.com
-d log.news.zing.vn
-d cdn.game.vietgiaitri.com
-d cover.vietgiaitri.com
-d adnet.vn
-d adtimaserver.vn
-d ads.xahoi.com.vn
-d blueserving.com
-d betrad.com
-d a.kickass.to
-d ab-gb.mgid.com
-d counter.yadro.ru
-d adnetwork.vn
-d optimizely.com
-d adzerk.net
-d doubleclick.net
-d cms.analytics.yahoo.com
-d google-analytics.com
-d y.analytics.yahoo.com
-d geo.query.yahoo.com
- /cv/ae/us/audience/
- /pagead/
